export const aiTools = [
  {
    id: 1,
    name: "ChatGPT",
    company: "OpenAI",
    category: "Chatbot & Text Generation",
    description: "Advanced AI chatbot powered by GPT-4 and GPT-5 models. Capable of conversation, writing, coding, analysis, and creative tasks.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",
    url: "https://chat.openai.com",
    pricing: "Free + Plus ($20/mo)",
    features: ["Text generation", "Code writing", "Image analysis", "File uploads", "Web browsing", "Plugin ecosystem"],
    tags: ["chatbot", "writing", "coding", "productivity"],
  },
  {
    id: 2,
    name: "Claude",
    company: "Anthropic",
    category: "Chatbot & Text Generation",
    description: "AI assistant built for safety, helpfulness, and honesty. Excels at long documents, coding, and nuanced reasoning.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Anthropic_logo.svg/512px-Anthropic_logo.svg.png",
    url: "https://claude.ai",
    pricing: "Free + Pro ($20/mo)",
    features: ["200K context window", "Code generation", "Document analysis", "Vision", "Artifacts", "Projects"],
    tags: ["chatbot", "writing", "coding", "analysis"],
  },
  {
    id: 3,
    name: "Gemini",
    company: "Google",
    category: "Chatbot & Text Generation",
    description: "Google's multimodal AI model. Integrated with Google services for search, email, docs, and more.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Google_Gemini_logo.svg/512px-Google_Gemini_logo.svg.png",
    url: "https://gemini.google.com",
    pricing: "Free + Advanced ($20/mo)",
    features: ["Multimodal", "Google integration", "Long context", "Code generation", "Image generation", "Real-time data"],
    tags: ["chatbot", "multimodal", "search", "productivity"],
  },
  {
    id: 4,
    name: "Midjourney",
    company: "Midjourney Inc.",
    category: "Image Generation",
    description: "Industry-leading AI image generator known for stunning artistic and photorealistic outputs.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Midjourney_Emblem.png/512px-Midjourney_Emblem.png",
    url: "https://www.midjourney.com",
    pricing: "From $10/mo",
    features: ["Text-to-image", "Style control", "Upscaling", "Variations", "Pan & zoom", "Web editor"],
    tags: ["image", "art", "design", "creative"],
  },
  {
    id: 5,
    name: "DALL-E 3",
    company: "OpenAI",
    category: "Image Generation",
    description: "OpenAI's latest image generation model with exceptional text rendering and prompt following.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",
    url: "https://openai.com/dall-e-3",
    pricing: "Included with ChatGPT Plus",
    features: ["Text-to-image", "Accurate text in images", "ChatGPT integration", "Editing", "Variations"],
    tags: ["image", "art", "design"],
  },
  {
    id: 6,
    name: "Stable Diffusion",
    company: "Stability AI",
    category: "Image Generation",
    description: "Open-source image generation model. Can be run locally or via cloud services. Highly customizable.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/sqzgmbkggvc1uwgapeuy",
    url: "https://stability.ai",
    pricing: "Free (open-source) + Cloud API",
    features: ["Open source", "Local deployment", "ControlNet", "Custom models", "Inpainting", "LoRA training"],
    tags: ["image", "open-source", "art", "customizable"],
  },
  {
    id: 7,
    name: "GitHub Copilot",
    company: "GitHub / Microsoft",
    category: "Code Assistant",
    description: "AI-powered code completion and chat assistant integrated into VS Code, JetBrains, and other IDEs.",
    logo: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
    url: "https://github.com/features/copilot",
    pricing: "Free (limited) + $10/mo",
    features: ["Code completion", "Chat", "Code explanation", "Test generation", "Multi-file editing", "CLI integration"],
    tags: ["coding", "development", "productivity"],
  },
  {
    id: 8,
    name: "Cursor",
    company: "Cursor Inc.",
    category: "Code Assistant",
    description: "AI-first code editor built on VS Code. Uses multiple AI models for coding assistance with full codebase awareness.",
    logo: "https://www.cursor.com/brand/icon.svg",
    url: "https://www.cursor.com",
    pricing: "Free + Pro ($20/mo)",
    features: ["AI code editor", "Codebase-aware", "Multi-model", "Tab completion", "Chat", "Composer mode"],
    tags: ["coding", "editor", "development"],
  },
  {
    id: 9,
    name: "Jasper",
    company: "Jasper AI",
    category: "Content Writing",
    description: "AI content platform for marketing teams. Generates blog posts, ads, emails, and social media content.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1492752557/clyser4ebfofkexjhsdf.png",
    url: "https://www.jasper.ai",
    pricing: "From $49/mo",
    features: ["Marketing copy", "Blog writing", "Brand voice", "Templates", "Chrome extension", "Team collaboration"],
    tags: ["writing", "marketing", "content"],
  },
  {
    id: 10,
    name: "Grammarly",
    company: "Grammarly Inc.",
    category: "Writing Assistant",
    description: "AI writing assistant for grammar, spelling, style, and tone. Now includes generative AI features.",
    logo: "https://static.grammarly.com/assets/files/efe028ce3d4517c080ef24b5012230dd/grammarly_logo.svg",
    url: "https://www.grammarly.com",
    pricing: "Free + Premium ($12/mo)",
    features: ["Grammar check", "Tone detection", "Plagiarism check", "AI writing", "Style suggestions", "Browser extension"],
    tags: ["writing", "grammar", "productivity"],
  },
  {
    id: 11,
    name: "Notion AI",
    company: "Notion",
    category: "Productivity",
    description: "AI integrated into Notion workspace. Summarizes, writes, edits, and brainstorms within your notes and docs.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Notion-logo.svg/512px-Notion-logo.svg.png",
    url: "https://www.notion.so/product/ai",
    pricing: "$10/mo add-on",
    features: ["Summarization", "Writing assistance", "Action items", "Translation", "Q&A on docs", "Auto-fill databases"],
    tags: ["productivity", "writing", "organization"],
  },
  {
    id: 12,
    name: "Perplexity AI",
    company: "Perplexity",
    category: "AI Search Engine",
    description: "AI-powered search engine that provides cited, accurate answers by searching the web in real-time.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Perplexity_AI_logo.png",
    url: "https://www.perplexity.ai",
    pricing: "Free + Pro ($20/mo)",
    features: ["AI search", "Cited sources", "Follow-up questions", "File upload", "Collections", "API access"],
    tags: ["search", "research", "knowledge"],
  },
  {
    id: 13,
    name: "ElevenLabs",
    company: "ElevenLabs",
    category: "Voice & Audio",
    description: "AI voice generation platform. Creates ultra-realistic speech, voice cloning, and dubbing.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/b5c0a629aa2a4012baf1cb8b26c0ce0e",
    url: "https://elevenlabs.io",
    pricing: "Free + From $5/mo",
    features: ["Text-to-speech", "Voice cloning", "28+ languages", "Dubbing", "Sound effects", "API access"],
    tags: ["voice", "audio", "speech", "dubbing"],
  },
  {
    id: 14,
    name: "Runway ML",
    company: "Runway",
    category: "Video Generation",
    description: "AI-powered creative suite for video generation, editing, and visual effects. Known for Gen-3 Alpha.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1508296060/mzdj9tbcxpcnjrb1ugwg.png",
    url: "https://runwayml.com",
    pricing: "Free + From $12/mo",
    features: ["Text-to-video", "Image-to-video", "Video editing", "Green screen", "Motion tracking", "Gen-3 Alpha"],
    tags: ["video", "creative", "editing"],
  },
  {
    id: 15,
    name: "Suno",
    company: "Suno AI",
    category: "Music Generation",
    description: "AI music generator that creates full songs with vocals, instruments, and lyrics from text prompts.",
    logo: "https://suno.com/favicon.ico",
    url: "https://suno.com",
    pricing: "Free + From $8/mo",
    features: ["Text-to-music", "Vocal generation", "Custom lyrics", "Full songs", "Multiple genres", "Remix"],
    tags: ["music", "audio", "creative"],
  },
  {
    id: 16,
    name: "Canva AI",
    company: "Canva",
    category: "Design",
    description: "AI-powered design platform with Magic Studio features including text-to-image, background removal, and more.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Canva_Logo.svg/512px-Canva_Logo.svg.png",
    url: "https://www.canva.com",
    pricing: "Free + Pro ($12.99/mo)",
    features: ["Magic Design", "Text-to-image", "Background remover", "Magic Write", "Brand Kit", "Templates"],
    tags: ["design", "marketing", "creative"],
  },
  {
    id: 17,
    name: "Synthesia",
    company: "Synthesia",
    category: "Video Generation",
    description: "AI video creation platform with realistic AI avatars. Create professional videos from text without cameras.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1498015455/nvfv6xeojb2cjhmpuasw.png",
    url: "https://www.synthesia.io",
    pricing: "From $22/mo",
    features: ["AI avatars", "160+ languages", "Text-to-video", "Custom avatars", "Templates", "Screen recording"],
    tags: ["video", "avatar", "presentation"],
  },
  {
    id: 18,
    name: "Hugging Face",
    company: "Hugging Face",
    category: "AI Platform & Models",
    description: "The largest open-source AI community. Host, share, and deploy ML models, datasets, and spaces.",
    logo: "https://huggingface.co/front/assets/huggingface_logo-noborder.svg",
    url: "https://huggingface.co",
    pricing: "Free + Pro ($9/mo)",
    features: ["Model hub", "Datasets", "Spaces", "Inference API", "AutoTrain", "Open-source models"],
    tags: ["platform", "open-source", "models", "developer"],
  },
  {
    id: 19,
    name: "Replicate",
    company: "Replicate",
    category: "AI Platform & Models",
    description: "Run open-source AI models in the cloud with a simple API. Deploy custom models easily.",
    logo: "https://replicate.com/favicon.ico",
    url: "https://replicate.com",
    pricing: "Pay per use (free credits)",
    features: ["Model hosting", "API access", "Custom models", "Fine-tuning", "Predictions", "Webhooks"],
    tags: ["platform", "api", "deployment", "developer"],
  },
  {
    id: 20,
    name: "Otter.ai",
    company: "Otter.ai",
    category: "Transcription & Meeting",
    description: "AI meeting assistant that records, transcribes, and summarizes meetings in real-time.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1497982855/yz7v2tyxhw3loxfiv6cj.png",
    url: "https://otter.ai",
    pricing: "Free + Pro ($8.33/mo)",
    features: ["Live transcription", "Meeting summary", "Action items", "Speaker ID", "Search", "Integrations"],
    tags: ["meeting", "transcription", "productivity"],
  },
  {
    id: 21,
    name: "Descript",
    company: "Descript",
    category: "Video & Audio Editing",
    description: "AI-powered video and podcast editor. Edit media by editing text. Includes AI voice, filler word removal.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1413931529/wgaqmjx43nxcqogplur9.png",
    url: "https://www.descript.com",
    pricing: "Free + From $24/mo",
    features: ["Text-based editing", "AI voice", "Filler word removal", "Screen recording", "Transcription", "Clips"],
    tags: ["video", "audio", "editing", "podcast"],
  },
  {
    id: 22,
    name: "Copy.ai",
    company: "Copy.ai",
    category: "Content Writing",
    description: "AI-powered copywriting tool for marketing teams. Generate blog posts, social media, and ad copy.",
    logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/60e09ad0a8234e7689247e6f2cc790f6",
    url: "https://www.copy.ai",
    pricing: "Free + From $49/mo",
    features: ["Marketing copy", "Blog wizard", "Social media", "Email campaigns", "Workflows", "Brand voice"],
    tags: ["writing", "marketing", "copywriting"],
  },
  {
    id: 23,
    name: "Leonardo.ai",
    company: "Leonardo Interactive",
    category: "Image Generation",
    description: "AI art and image generation platform with fine-tuned models for game assets, concept art, and design.",
    logo: "https://leonardo.ai/favicon.ico",
    url: "https://leonardo.ai",
    pricing: "Free + From $10/mo",
    features: ["Image generation", "Fine-tuned models", "Canvas editor", "Texture generation", "3D assets", "Real-time gen"],
    tags: ["image", "art", "game-design", "3d"],
  },
  {
    id: 24,
    name: "Zapier AI",
    company: "Zapier",
    category: "Automation",
    description: "AI-powered automation platform connecting 6,000+ apps. Create workflows with natural language.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Zapier_logo.svg/512px-Zapier_logo.svg.png",
    url: "https://zapier.com",
    pricing: "Free + From $19.99/mo",
    features: ["AI automation", "6000+ integrations", "Natural language setup", "Chatbots", "Tables", "Interfaces"],
    tags: ["automation", "workflow", "integration", "no-code"],
  },
  {
    id: 25,
    name: "Vercel v0",
    company: "Vercel",
    category: "Code Assistant",
    description: "AI-powered UI generation tool. Describe a UI component and get production-ready React/Next.js code.",
    logo: "https://v0.dev/favicon.ico",
    url: "https://v0.dev",
    pricing: "Free + Premium",
    features: ["UI generation", "React/Next.js code", "Shadcn/ui", "Tailwind CSS", "Component editing", "Export to project"],
    tags: ["coding", "ui", "design", "frontend"],
  },
  {
    id: 26,
    name: "Bolt.new",
    company: "StackBlitz",
    category: "Code Assistant",
    description: "AI full-stack web development agent. Build, run, and deploy full applications from a prompt in the browser.",
    logo: "https://bolt.new/favicon.ico",
    url: "https://bolt.new",
    pricing: "Free + From $20/mo",
    features: ["Full-stack generation", "In-browser IDE", "Live preview", "Deploy to Netlify", "Multi-file projects", "Package management"],
    tags: ["coding", "full-stack", "deployment"],
  },
  {
    id: 27,
    name: "Lovable",
    company: "Lovable",
    category: "Code Assistant",
    description: "AI software engineer that builds full-stack web apps from natural language descriptions with deployment.",
    logo: "https://lovable.dev/favicon.ico",
    url: "https://lovable.dev",
    pricing: "Free + From $20/mo",
    features: ["Full-stack apps", "Supabase integration", "GitHub sync", "Auto deployment", "Real-time preview", "Iterative editing"],
    tags: ["coding", "no-code", "full-stack", "deployment"],
  },
  {
    id: 28,
    name: "Sora",
    company: "OpenAI",
    category: "Video Generation",
    description: "OpenAI's text-to-video model capable of generating realistic and imaginative video scenes from text prompts.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",
    url: "https://sora.com",
    pricing: "Included with ChatGPT Plus/Pro",
    features: ["Text-to-video", "Image-to-video", "Video editing", "Storyboard", "Remix", "High resolution"],
    tags: ["video", "creative", "generation"],
  },
  {
    id: 29,
    name: "Adobe Firefly",
    company: "Adobe",
    category: "Image Generation",
    description: "Adobe's generative AI integrated into Creative Cloud. Commercially safe image generation and editing.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Adobe_Corporate_logo.svg/512px-Adobe_Corporate_logo.svg.png",
    url: "https://firefly.adobe.com",
    pricing: "Free + Creative Cloud",
    features: ["Text-to-image", "Generative fill", "Text effects", "Commercially safe", "Photoshop integration", "Vector generation"],
    tags: ["image", "design", "creative", "commercial"],
  },
  {
    id: 30,
    name: "Whisper",
    company: "OpenAI",
    category: "Speech-to-Text",
    description: "Open-source speech recognition model by OpenAI. Supports 99 languages with high accuracy.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",
    url: "https://github.com/openai/whisper",
    pricing: "Free (open-source)",
    features: ["99 languages", "Transcription", "Translation", "Timestamps", "Open source", "Local deployment"],
    tags: ["speech", "transcription", "open-source"],
  },
];

export const aiCategories = [
  "All",
  "Chatbot & Text Generation",
  "Image Generation",
  "Video Generation",
  "Code Assistant",
  "Content Writing",
  "Writing Assistant",
  "Voice & Audio",
  "Music Generation",
  "Design",
  "AI Search Engine",
  "AI Platform & Models",
  "Transcription & Meeting",
  "Video & Audio Editing",
  "Automation",
  "Productivity",
  "Speech-to-Text",
];
